[[collection]]
type="box"
img="/assets/contact.svg"
link="mailto:<team@iaculus.xyz"
rotate=true
title="Contact"
subtitle="For consulting on existing automated workflows or a greenfield agentic system, please reach out."
