[[collection]]
type = "card_simple"
icon = "/assets/kubernetes.png"
title = "Kubernetes"
content = "Embedded LLM Reasoning"

[[collection]]
type = "card_simple"
icon = "/assets/rust.png"
title = "Rust"
content = "Scalable Agent Systems"

[[collection]]
type = "card_simple"
icon = "/assets/roadmap.png"
title = "Agentic Roadmapping"
content = "Proactive Systems Thinking"
