[[collection]]
type = "card_simple"
icon = "/assets/kubernetes.svg"
title = "Kubernetes"
content = "Embedded LLM Reasoning"

[[collection]]
type = "card_simple"
icon = "/assets/rust.svg"
title = "Rust"
content = "Scalable Agent Systems"

[[collection]]
type = "card_simple"
icon = "/assets/roadmap.svg"
title = "Agentic Roadmapping"
content = "Proactive Systems Thinking"
